name: naruhodo
description: "Naruhodo project."
publish_to: "none"

version: 1.0.10+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.1.5
  flip_card: ^0.7.0
  flutter_tts: ^3.8.5
  percent_indicator: ^4.2.3
  speech_to_text: ^6.6.0
  awesome_snackbar_content: ^0.1.3
  lottie: ^3.1.0
  google_fonts: ^6.1.0
  flutter_carousel_widget: ^2.2.0
  smooth_page_indicator: ^1.1.0
  animations: ^2.0.11
  card_swiper: ^3.0.1
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.1.0
  audioplayers: ^6.0.0
  firebase_storage: ^11.7.4
  http: ^1.2.1
  encrypt: ^5.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  fake_cloud_firestore: ^2.5.1
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon/logo.png"
  image_path_android: "assets/icon/logo_round.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: noto_sans
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
  assets:
    - assets/icons/
    - assets/animations/
    - assets/data/voca/N5/
    - assets/data/voca/N4/
    - assets/data/voca/N3/
    - assets/data/hiragana/
    - assets/data/katakana/
    - assets/data/patterns/
    - assets/data/section/

flutter_intl:
  enabled: true
  arb_dir: lib/util/lang/l10n
  output_dir: lib/util/lang/generated
